export const positionsBySport: Record<string, readonly string[]> = {
  Baseball: ['Pitcher', 'Catcher', 'First Base', 'Second Base', 'Third Base', 'Shortstop', 'Outfield', 'Utility'],
  'Beach volleyball': ['Setter', 'Defender', 'Blocker'],
  Fencing: ['Foil', 'Épée', 'Sabre'],
  'Field hockey': ['Goalkeeper', 'Defender', 'Midfielder', 'Forward'],
  Football: ['Quarterback', 'Running Back', 'Fullback', 'Wide Receiver', 'Tight End', 'Offensive Line', 'Defensive Line', 'Linebacker', 'Cornerback', 'Safety', 'Specialist'],
  Gymnastics: ['All-Around', 'Vault', 'Uneven Bars', 'Balance Beam', 'Floor Exercise'],
  Softball: ['Pitcher', 'Catcher', 'First Base', 'Second Base', 'Third Base', 'Shortstop', 'Outfield', 'Utility'],
  "Men's basketball": ['Point Guard', 'Shooting Guard', 'Small Forward', 'Power Forward', 'Center'],
  "Women's basketball": ['Point Guard', 'Shooting Guard', 'Small Forward', 'Power Forward', 'Center'],
  "Men's cross country": ['Distance Runner'],
  "Women's cross country": ['Distance Runner'],
  "Men's golf": ['Golfer'],
  "Women's golf": ['Golfer'],
  "Men's ice hockey": ['Goaltender', 'Defenseman', 'Left Wing', 'Right Wing', 'Center'],
  "Women's ice hockey": ['Goaltender', 'Defenseman', 'Left Wing', 'Right Wing', 'Center'],
  "Men's lacrosse": ['Goalie', 'Defense', 'Long Stick Midfielder', 'Short Stick Midfielder', 'Faceoff Specialist', 'Attack'],
  "Women's lacrosse": ['Goalkeeper', 'Defense', 'Midfield', 'Draw Specialist', 'Attack'],
  "Men's rowing": ['Coxswain', 'Rowing Athlete'],
  "Women's rowing": ['Coxswain', 'Rowing Athlete'],
  "Men's soccer": ['Goalkeeper', 'Defender', 'Midfielder', 'Forward'],
  "Women's soccer": ['Goalkeeper', 'Defender', 'Midfielder', 'Forward'],
  "Men's swimming and diving": ['Freestyle', 'Backstroke', 'Breaststroke', 'Butterfly', 'Individual Medley', 'Diver'],
  "Women's swimming and diving": ['Freestyle', 'Backstroke', 'Breaststroke', 'Butterfly', 'Individual Medley', 'Diver'],
  "Men's tennis": ['Singles', 'Doubles'],
  "Women's tennis": ['Singles', 'Doubles'],
  "Men's track and field": ['Sprints', 'Middle Distance', 'Distance', 'Hurdles', 'Jumps', 'Throws', 'Pole Vault', 'Multi-Events'],
  "Women's track and field": ['Sprints', 'Middle Distance', 'Distance', 'Hurdles', 'Jumps', 'Throws', 'Pole Vault', 'Multi-Events'],
  "Men's volleyball": ['Setter', 'Outside Hitter', 'Opposite Hitter', 'Middle Blocker', 'Libero', 'Defensive Specialist'],
  "Women's volleyball": ['Setter', 'Outside Hitter', 'Opposite Hitter', 'Middle Blocker', 'Libero', 'Defensive Specialist'],
  "Men's water polo": ['Goalkeeper', 'Field Player'],
  "Women's water polo": ['Goalkeeper', 'Field Player'],
  "Men's wrestling": ['Wrestler'],
  "Women's wrestling": ['Wrestler'],
  Other: ['Other'],
};

export function getPositions(sport: string) {
  return positionsBySport[sport] ?? [];
}
